#include "stdafx.h"
#include "HotkeySchemeParser.h"
#include "../resource.h"
#include <wchar.h>
#include "../Utils/Strings.h"

void HotkeySchemeParser::PopulateDefaultScheme()
{
  // This will populate |m_list| with hard coded default hotkey scheme settings.
  // At the time this was written, it's copied directly from the original hotkey definition
  // in CMPlayerCApp::Settings::UpdateData of mplayerc.cpp

  m_schemename = L"SPlayer";

#define ADDCMD(cmd) m_list.push_back(HotkeyCmd##cmd)

  ADDCMD((ID_BOSS, VK_OEM_3, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_BOSS_KEY));
  ADDCMD((ID_PLAY_PLAYPAUSE, VK_SPACE, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PLAY_PAUSE, APPCOMMAND_MEDIA_PLAY_PAUSE, HotkeyCmd::LDOWN));
  ADDCMD((ID_PLAY_SEEKFORWARDSMALL, VK_RIGHT, FVIRTKEY|FNOINVERT, IDS_HOTKEY_SEEK_FORWARD_SMALL,APPCOMMAND_MEDIA_FAST_FORWARD));
  ADDCMD((ID_PLAY_SEEKBACKWARDSMALL, VK_LEFT, FVIRTKEY|FNOINVERT, IDS_HOTKEY_SEEK_BACKWARD_SMALL,APPCOMMAND_MEDIA_REWIND));


  ADDCMD((ID_FILE_OPENQUICK, 'Q', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_FILEOPEN_QUICK));
  ADDCMD((ID_FILE_OPENURLSTREAM, 'U', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_FILEOPEN_URL));
  ADDCMD((ID_FILE_OPENMEDIA, 'O', FVIRTKEY|FCONTROL|FNOINVERT ,IDS_HOTKEY_FILEOPEN_NORMAL));
  ADDCMD((ID_FILE_OPENFOLDER, 'F', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_FILEOPEN_FOLDER));

  ADDCMD((ID_SUBMOVEUP,  VK_OEM_4 /* [ */, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SUBTITLE_MOVE_UP));
  ADDCMD((ID_SUBMOVEDOWN,  VK_OEM_6  /* ] */, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SUBTITLE_MOVE_DOWN));
  ADDCMD((ID_SUB2MOVEUP,  VK_OEM_4, FVIRTKEY|FALT|FCONTROL|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_MOVE_UP));
  ADDCMD((ID_SUB2MOVEDOWN,  VK_OEM_6, FVIRTKEY|FALT|FCONTROL|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_MOVE_DOWN));
  ADDCMD((ID_SUBFONTDOWNBOTH,  VK_F1, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SUBTITLE_FONT_SHRINK));
  ADDCMD((ID_SUBFONTUPBOTH,  VK_F2, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SUBTITLE_FONT_ENLARGE));
  ADDCMD((ID_SUB1FONTDOWN,  VK_F3, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_1ST_FONT_SHRINK));
  ADDCMD((ID_SUB1FONTUP,  VK_F4, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_1ST_FONT_ENLARGE));
  ADDCMD((ID_SUB2FONTDOWN,  VK_F5, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_FONT_SHRINK));
  ADDCMD((ID_SUB2FONTUP,  VK_F6, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_FONT_ENLARGE));

  ADDCMD((ID_SUB_DELAY_DOWN, VK_F1, FVIRTKEY|FNOINVERT, IDS_HOTKEY_SUBTITLE_1ST_DELAY_REDUCE));
  ADDCMD((ID_SUB_DELAY_UP, VK_F2,   FVIRTKEY|FNOINVERT, IDS_HOTKEY_SUBTITLE_1ST_DELAY_PLUS));
  ADDCMD((ID_SUB_DELAY_DOWN2, VK_F1, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_DELAY_REDUCE));
  ADDCMD((ID_SUB_DELAY_UP2, VK_F2,   FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_2ND_DELAY_PLUS));
  ADDCMD((ID_SHOW_VIDEO_STAT_OSD,  VK_TAB, FVIRTKEY|FNOINVERT, IDS_HOTKEY_SHOW_VIDEO_STAT_OSD));
  ADDCMD((ID_BRIGHTINC, VK_HOME, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_BRIGHT_MORE));
  ADDCMD((ID_BRIGHTDEC, VK_END, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_BRIGHT_LESS));
  ADDCMD((ID_ABCONTROL_TOGGLE,  VK_F7, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_ABCONTROL_TOGGEL));
  ADDCMD((ID_ABCONTROL_SETA,  VK_F8, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_ABCONTROL_SETA));
  ADDCMD((ID_ABCONTROL_SETB,  VK_F9, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_ABCONTROL_SETB));
  ADDCMD((ID_FILE_OPENDVD, 'D', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_FILEOPEN_DVD));
  ADDCMD((ID_FILE_OPENBDVD, 'B', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_FILEOPEN_BD));
  ADDCMD((ID_FILE_OPENDEVICE, 'V', FVIRTKEY|FCONTROL|FNOINVERT, IDS_FILE_OPENDEVICE));
  ADDCMD((ID_FILE_SAVE_COPY, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_FILE_SAVEAS));
  ADDCMD((ID_FILE_SAVE_IMAGE, 'I', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_IMAGE_SAVEAS));
  ADDCMD((ID_FILE_SAVE_IMAGE_AUTO, VK_F5, FVIRTKEY|FNOINVERT, IDS_HOTKEY_IMAGE_SAVE_AUTO));
  ADDCMD((ID_FILE_LOAD_SUBTITLE, 'L', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_LOAD_SUBTITLE));
  ADDCMD((ID_FILE_SAVE_SUBTITLE, 'S', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SAVE_SUBTITLE));
  ADDCMD((ID_FILE_COPYTOCLIPBOARD, 'C', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_COPY_IMAGE_TO_CLIPBOARD));
  ADDCMD((ID_FILE_PROPERTIES, VK_F10, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_FILE_PROPERTIES));
  ADDCMD((ID_FILE_EXIT, 'X', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_FILE_EXIT));
  ADDCMD((ID_TOGGLE_SUBTITLE, 'H', FVIRTKEY|FNOINVERT, IDS_HOTKEY_SUBTITLE_TOGGLE));
  ADDCMD((ID_VIEW_VF_FROMINSIDE, 'C', FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_RESET));
  ADDCMD((ID_PLAY_PLAY, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PLAY_PLAY,APPCOMMAND_MEDIA_PLAY));
  ADDCMD((ID_PLAY_PAUSE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PLAY_PAUSE,APPCOMMAND_MEDIA_PAUSE));
  ADDCMD((ID_PLAY_MANUAL_STOP, VK_OEM_PERIOD, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PLAY_STOP, APPCOMMAND_MEDIA_STOP));
  ADDCMD((ID_PLAY_FRAMESTEP, VK_RIGHT, FVIRTKEY|FCONTROL|FALT|FNOINVERT, IDS_HOTKEY_PLAY_FRAMESTEP));
  ADDCMD((ID_PLAY_FRAMESTEPCANCEL, VK_LEFT, FVIRTKEY|FCONTROL|FALT|FNOINVERT, IDS_HOTKEY_PLAY_FRAMESTEP_BACK));
  ADDCMD((ID_PLAY_INCRATE, VK_UP, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PLAY_INCREASE_RATE));
  ADDCMD((ID_PLAY_DECRATE, VK_DOWN, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PLAY_DECREASE_RATE));
  ADDCMD((ID_VIEW_FULLSCREEN, VK_RETURN, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_TOGGLE_FULLSCREEN, 0, HotkeyCmd::LDBLCLK));
  ADDCMD((ID_VIEW_FULLSCREEN, VK_RETURN, FVIRTKEY|FNOINVERT, IDS_HOTKEY_TOGGLE_FULLSCREEN, 0, HotkeyCmd::MUP));
  ADDCMD((ID_PLAY_INCAUDDELAY, VK_ADD, FVIRTKEY|FNOINVERT, IDS_HOTKEY_AUDIO_DELAY_PLUS));
  ADDCMD((ID_PLAY_DECAUDDELAY, VK_SUBTRACT, FVIRTKEY|FNOINVERT, IDS_HOTKEY_AUDIO_DELAY_REDUCE));
  ADDCMD((ID_VIEW_PLAYLIST, 'P', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_PLAYLIST));
  ADDCMD((ID_VIEW_PLAYLIST, '7', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_PLAYLIST));
  ADDCMD((ID_PLAY_RESETRATE, 'R', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PLAY_RESET_PLAYRATE));
  ADDCMD((ID_PLAY_SEEKFORWARDMED, VK_RIGHT, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SEEKFORWARDMED));
  ADDCMD((ID_PLAY_SEEKBACKWARDMED, VK_LEFT, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SEEKBACKFORD));
  ADDCMD((ID_PLAY_SEEKFORWARDLARGE, VK_RIGHT, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SEEK_FORWARD_BIG));
  ADDCMD((ID_PLAY_SEEKBACKWARDLARGE, VK_LEFT, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SEEK_BACKWARD_BIG));
  ADDCMD((ID_PLAY_SEEKKEYFORWARD, VK_RIGHT, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SEEK_FORWARD_KEYFRAME));
  ADDCMD((ID_PLAY_SEEKKEYBACKWARD, VK_LEFT, FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SEEK_BACKWARD_KEYFRAME));
  ADDCMD((ID_NAVIGATE_SKIPFORWARD, VK_NEXT, FVIRTKEY|FNOINVERT, IDS_HOTKEY_NAV_SKIP_FORWARD, APPCOMMAND_MEDIA_NEXTTRACK, HotkeyCmd::X2DOWN));
  ADDCMD((ID_NAVIGATE_SKIPBACK, VK_PRIOR, FVIRTKEY|FNOINVERT, IDS_HOTKEY_NAV_SKIP_BACKWARD, APPCOMMAND_MEDIA_PREVIOUSTRACK, HotkeyCmd::X1DOWN));
  ADDCMD((ID_NAVIGATE_SKIPFORWARDPLITEM, VK_NEXT, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_NAV_SKIP_FORWARD_PLITEM));
  ADDCMD((ID_NAVIGATE_SKIPBACKPLITEM, VK_PRIOR, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_NAV_SKIP_BACKWARD_PLITEM));
  ADDCMD((ID_VIEW_CAPTIONMENU, '0', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_CAPTION_MENU));
  ADDCMD((ID_VIEW_SEEKER, '1', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_SEEK_BAR));
  ADDCMD((ID_VIEW_CONTROLS, '2', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_TOOL_BAR));
  ADDCMD((ID_SHOWTRANSPRANTBAR, '5', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_TRANSPARENT_CONTROL_DIALOG));
  ADDCMD((ID_VIEW_CAPTURE, '8', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_CAPTURE_PANEL));
  ADDCMD((ID_VIEW_SHADEREDITOR, '9', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_SHADER_EDITOR_PANEL));
  ADDCMD((ID_VIEW_PRESETS_MINIMAL, '1', FVIRTKEY|FNOINVERT, IDS_HOTKEY_UI_PRESET_MINIMAL));
  ADDCMD((ID_VIEW_PRESETS_COMPACT, '2', FVIRTKEY|FNOINVERT, IDS_HOTKEY_UI_PRESET_COMPACT));
  ADDCMD((ID_VIEW_PRESETS_NORMAL, '3', FVIRTKEY|FNOINVERT, IDS_VIEW_PRESETS_NORMAL));
  ADDCMD((ID_VIEW_FULLSCREEN_SECONDARY, VK_F11, FVIRTKEY|FNOINVERT, IDS_HOTKEY_TOGGLE_FULLSCREEN_SECONDARY));
  ADDCMD((ID_VIEW_ZOOM_50, '1', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_ZOOM_50));
  ADDCMD((ID_VIEW_ZOOM_100, '2', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_ZOOM_100));
  ADDCMD((ID_VIEW_ZOOM_200, '3', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_ZOOM_200));
  ADDCMD((ID_VIEW_ZOOM_AUTOFIT, '4', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_ZOOM_AUTOFIT));
  ADDCMD((ID_ASPECTRATIO_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_ASPECT_RATIO_NEXT));
  ADDCMD((ID_VIEW_VF_HALF, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VIDEO_FRAME_50));
  ADDCMD((ID_VIEW_VF_NORMAL, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VIDEO_FRAME_100));
  ADDCMD((ID_VIEW_VF_DOUBLE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VIDEO_FRAME_200));
  ADDCMD((ID_VIEW_VF_STRETCH, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VIDEO_FRAME_STRETCH));
  ADDCMD((ID_VIEW_VF_FROMINSIDE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_RESET));
  ADDCMD((ID_VIEW_VF_FROMOUTSIDE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VIDEO_FRAME_STANDARD));
  ADDCMD((ID_SWITCH_AUDIO_DEVICE, 'A', FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_SWITCH_AUDIO_DEVICE));
  ADDCMD((ID_ONTOP_ALWAYS, 'T', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PIN_ONTOP_ALWAYS));
  ADDCMD((ID_PLAY_GOTO, 'G', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PLAY_GOTO));
  ADDCMD((ID_VIEW_RESET, VK_NUMPAD5, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_RESET));
  ADDCMD((ID_VIEW_INCSIZE, VK_NUMPAD9, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_SIZE_PLUS));
  ADDCMD((ID_VIEW_INCWIDTH, VK_NUMPAD6, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_WIDTH_PLUS));
  ADDCMD((ID_VIEW_INCHEIGHT, VK_NUMPAD8, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_HEIGHT_PLUS));
  ADDCMD((ID_VIEW_DECSIZE, VK_NUMPAD1, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_SIZE_REDUCE));
  ADDCMD((ID_VIEW_DECWIDTH, VK_NUMPAD4, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_WIDTH_REDUCE));
  ADDCMD((ID_VIEW_DECHEIGHT, VK_NUMPAD2, FVIRTKEY|FNOINVERT, IDS_HOTKEY_PANSCAN_HEIGHT_REDUCE));
  ADDCMD((ID_PANSCAN_CENTER, VK_NUMPAD5, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_CENTER));
  ADDCMD((ID_PANSCAN_MOVELEFT, VK_NUMPAD4, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_LEFT));
  ADDCMD((ID_PANSCAN_MOVERIGHT, VK_NUMPAD6, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_RIGHT));
  ADDCMD((ID_PANSCAN_MOVEUP, VK_NUMPAD8, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_UP));
  ADDCMD((ID_PANSCAN_MOVEDOWN, VK_NUMPAD2, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_DOWN));
  ADDCMD((ID_PANSCAN_MOVEUPLEFT, VK_NUMPAD7, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_UPLEFT));
  ADDCMD((ID_PANSCAN_MOVEUPRIGHT, VK_NUMPAD9, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_UPRIGHT));
  ADDCMD((ID_PANSCAN_MOVEDOWNLEFT, VK_NUMPAD1, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_BOTTOMLEFT));
  ADDCMD((ID_PANSCAN_MOVEDOWNRIGHT, VK_NUMPAD3, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_PANSCAN_MOVE_BOTTOMRIGHT));
  ADDCMD((ID_PANSCAN_ROTATEXP, VK_NUMPAD8, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_X_PLUS));
  ADDCMD((ID_PANSCAN_ROTATEXM, VK_NUMPAD2, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_X_REDUCE));
  ADDCMD((ID_PANSCAN_ROTATEYP, VK_NUMPAD4, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_Y_PLUS));
  ADDCMD((ID_PANSCAN_ROTATEYM, VK_NUMPAD6, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_Y_REDUCE));
  ADDCMD((ID_PANSCAN_ROTATEZP, VK_NUMPAD1, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_Z_PLUS));
  ADDCMD((ID_PANSCAN_ROTATEZM, VK_NUMPAD3, FVIRTKEY|FALT|FNOINVERT, IDS_HOTKEY_PANSCAN_ROTATE_Z_REDUCE));
  ADDCMD((ID_VOLUME_UP, VK_UP, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VOLUME_UP, 0, HotkeyCmd::WUP));//APPCOMMAND_VOLUME_UP
  ADDCMD((ID_VOLUME_DOWN, VK_DOWN, FVIRTKEY|FNOINVERT, IDS_HOTKEY_VOLUME_DOWN, 0, HotkeyCmd::WDOWN));//APPCOMMAND_VOLUME_DOWN
  ADDCMD((ID_VOLUME_MUTE, 'M', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_VOLUME_MUTE, APPCOMMAND_VOLUME_MUTE));//APPCOMMAND_VOLUME_MUTE
  ADDCMD((ID_NAVIGATE_TITLEMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_TITLEMENU));
  ADDCMD((ID_NAVIGATE_ROOTMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_ROOTMENU));
  ADDCMD((ID_NAVIGATE_SUBPICTUREMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_SUBTITLE_MENU));
  ADDCMD((ID_NAVIGATE_AUDIOMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_AUDIO_MENU));
  ADDCMD((ID_NAVIGATE_ANGLEMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_ANGLE_MENU));
  ADDCMD((ID_NAVIGATE_CHAPTERMENU, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_CHAP_MENU));
  ADDCMD((ID_NAVIGATE_MENU_LEFT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_LEFT));
  ADDCMD((ID_NAVIGATE_MENU_RIGHT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_RIGHT));
  ADDCMD((ID_NAVIGATE_MENU_UP, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_UP));
  ADDCMD((ID_NAVIGATE_MENU_DOWN, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_DOWN));
  ADDCMD((ID_NAVIGATE_MENU_ACTIVATE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_OK));
  ADDCMD((ID_NAVIGATE_MENU_BACK, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_RETURN));
  ADDCMD((ID_NAVIGATE_MENU_LEAVE, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_EXIT));
  ADDCMD((ID_DVD_SUB_ONOFF, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_TOGGLE_SUBTITLE));
  ADDCMD((ID_DVD_ANGLE_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_ANGLE_NEXT));
  ADDCMD((ID_DVD_ANGLE_PREV, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_ANGLE_PREV));
  ADDCMD((ID_DVD_AUDIO_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_AUDIO_NEXT));
  ADDCMD((ID_DVD_AUDIO_PREV, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_AUDIO_PREV));
  ADDCMD((ID_DVD_SUB_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_SUBTITLE_NEXT));
  ADDCMD((ID_DVD_SUB_PREV, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_DVD_MENU_CONTROL_SUBTITLE_PREV));
  ADDCMD((ID_MENU_PLAYER_SHORT, 0, FVIRTKEY|FNOINVERT, IDS_MENU_PLAYER_SHORT, 0, HotkeyCmd::RUP));
  ADDCMD((ID_VIEW_OPTIONS, 'O', FVIRTKEY|FNOINVERT, IDS_HOTKEY_SETTING_PANEL));
  ADDCMD((ID_STREAM_AUDIO_NEXT, 'A', FVIRTKEY|FNOINVERT, IDS_HOTKEY_AUDIO_STREAM_NEXT));
  ADDCMD((ID_STREAM_AUDIO_PREV, 'A', FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_AUDIO_STREAM_PREV));
  ADDCMD((ID_STREAM_SUB_NEXT, 'S', FVIRTKEY|FNOINVERT, IDS_HOTKEY_SUBTITLE_NEXT));
  ADDCMD((ID_STREAM_SUB_PREV, 'S', FVIRTKEY|FSHIFT|FNOINVERT, IDS_HOTKEY_SUBTITLE_PREV));
  ADDCMD((ID_STREAM_SUB_ONOFF, 'W', FVIRTKEY|FNOINVERT, IDS_HOTKEY_STEAM_SUBTITLE_TOGGLE));
  ADDCMD((ID_OGM_AUDIO_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_OGM_AUDIO_STREAM_NEXT));
  ADDCMD((ID_OGM_AUDIO_PREV, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_OGM_AUDIO_STREAM_PREV));
  ADDCMD((ID_OGM_SUB_NEXT, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_OGM_SUBTITLE_NEXT));
  ADDCMD((ID_OGM_SUB_PREV, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_OGM_SUBTITLE_PREV));
  ADDCMD((ID_VSYNC_OFFSET_MORE, VK_UP, FVIRTKEY|FALT|FCONTROL|FSHIFT|FNOINVERT, IDS_HOTKEY_VSYNC_OFFSET_MORE));
  ADDCMD((ID_VSYNC_OFFSET_LESS, VK_DOWN, FVIRTKEY|FALT|FCONTROL|FSHIFT|FNOINVERT, IDS_HOTKEY_VSYNC_OFFSET_LESS));
  ADDCMD((ID_SHOWDRAWSTAT, 'J', FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_TOGGLE_RENDER_STATUS));
  ADDCMD((ID_PLAYLIST_DELETEITEM, VK_DELETE, FVIRTKEY|FNOINVERT, IDS_PLAYLIST_DELETEITEM));
  ADDCMD((ID_SEEK_TO_BEGINNING,VK_HOME, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SEEK_TO_BEGINNING));
  ADDCMD((ID_SEEK_TO_MIDDLE, VK_DELETE, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SEEK_TO_MIDDLE));
  ADDCMD((ID_SEEK_TO_END, VK_END, FVIRTKEY|FCONTROL|FNOINVERT, IDS_HOTKEY_SEEK_TO_END));
  ADDCMD((ID_SUBTITLES_SUBITEM_RELOAD, 0, FVIRTKEY|FNOINVERT, IDS_HOTKEY_SUBTITLE_RELOAD));

#undef ADDCMD
}

bool HotkeySchemeParser::ReadFromFile(const wchar_t* filename)
{
  // reset
  m_list.resize(0);
  m_schemename.resize(0);

  // open file
  FILE* file = NULL;
  if (_wfopen_s(&file, filename, L"rb") != 0)
    return false;

  // validate bom
  wchar_t bom = 0;
  if (fread(&bom, sizeof(wchar_t), 1, file) != 1)
    return false;

  if (bom != 0xfeff)
    return false;

  // a single buffer for the file
  std::vector<wchar_t> buffer;
  size_t chars_read = 0;
  wchar_t pass_buf[1024];
  while (true)
  {
    chars_read = fread(pass_buf, sizeof(wchar_t), 1024, file);
    if (chars_read > 0)
    {
      buffer.resize(buffer.size() + chars_read);
      memcpy(&buffer[buffer.size() - chars_read], pass_buf, chars_read * sizeof(wchar_t));
    }
    if (chars_read < 1024)
      break;
  }

  if (buffer.size() == 0)
    return false;

  // parse buffer to lines
  std::vector<wchar_t>::iterator it_pos = buffer.begin();
  for (std::vector<wchar_t>::iterator it = buffer.begin(); it != buffer.end(); it++)
  {
    if (*it == L'\n')
    {
      std::wstring line(&(*it_pos), std::distance(it_pos, it));
      it_pos = it;
      Strings::Trim(line);
      if (line.length() == 0)
        continue;
      //skip the commentary
      if (line.find(L'/') == 0)
        continue;

      // scan this line for possible input values

      // check scheme name
      if (m_schemename.length() == 0)
      {
        size_t bracket_l = line.find(L'[');
        size_t bracket_r = line.find(L']');
        if (bracket_l == 0 && bracket_r > 0 && bracket_r != std::wstring::npos)
        {
          m_schemename.assign(line.c_str()+1, bracket_r-1);
          continue;
        }
      }

      // find comment mark
      if (line.find('/') != std::wstring::npos)
      {
        line = line.substr(0, line.find('/'));
        Strings::Trim(line);
      }
      // find equation mark
      size_t equal_mark = line.find(L'=');
      if (equal_mark == 0 || equal_mark == std::wstring::npos)
        continue;

      // cmd id
      std::wstring cmd_s(line.c_str(), equal_mark);
      int cmd = GetCmdCodeByCmdName(cmd_s.c_str());
      
      // others
      std::vector<unsigned int> params;
      size_t pos_start = equal_mark + 1;
      int paramindex   = 0;
      wchar_t* end_ptr;
      while (true)
      {
        std::wstring field;
        unsigned int paramcode;
        size_t pos_comma = line.find(L',', pos_start);
        if (pos_comma != std::wstring::npos)
        {
          field.assign(line.c_str() + pos_start + 1, pos_comma - pos_start - 1);
          pos_start = pos_comma + 1;
        }
        else
          field.assign(line.c_str() + pos_start + 1, line.length() - pos_start - 1);

        switch (paramindex)
        {
        case 0:
          paramcode = GetKeyCodeByKeyName(field);
          break;
        case 1:
          paramcode = GetVirtCodeByVirtName(field);
          break;
        case 2:
          paramcode = GetAppCmdCodeByAppCmdName(field);
          break;
        case 3:
          paramcode = GetMouseCodeByMouseName(field);
          break;
        }
        params.push_back(paramcode);
        paramindex++;
        if (pos_comma == std::wstring::npos)
          break;
      }

      if (params.size() == 4)
        m_list.push_back(HotkeyCmd(cmd, params[0], params[1], 0, params[2], params[3]));
      else if (params.size() == 2)
        m_list.push_back(HotkeyCmd(cmd, params[0], params[1], 0));
    }
  }

  return true;
}

bool HotkeySchemeParser::WriteToFile(const wchar_t* filename)
{
  // File format [UTF-16 encoded with BOM, line break is CRLF]
  // --------------------------------------------------------
  // //HERE IS THE COMMENTARY SUCH AS:
  // //请勿直接编辑本文件，请复制以创建新的快捷键方案
  // //您可以将您的自定义方案通过EMAIL发送给我们，加入到官方方案库中
  // [Hotkey Scheme Name]
  // ID_BOSS = VK_OEM_3, FVIRTKEY|FNOINVERT|FCONTROL //老板键
  // ID_PLAY_PLAYPAUSE = VK_SPACE, FVIRTKEY|FNOINVERT, APPCOMMAND_MEDIA_PLAY_PAUSE, LDOWN //播放/暂停
  // --------------------------------------------------------
  std::vector<std::wstring> linefeeds;
  linefeeds.push_back((LPCTSTR)CString(MAKEINTRESOURCE(IDS_HOTKEY_COMMENTARY)));
  wchar_t line[512];
  swprintf_s(line, 512, L"[%s]\r\n", m_schemename.c_str());
  linefeeds.push_back(line);
  
  unsigned int appcmd;
  unsigned int mouse;
  unsigned int virt;
  unsigned int key;
  for (std::vector<HotkeyCmd>::iterator it = m_list.begin(); it != m_list.end(); it++)
  {
    // note: we choose to put everything to (unsigned int) for safe conversion
    appcmd  = it->appcmd;
    mouse   = it->mouse;
    virt    = it->fVirt;
    key     = it->key;
    if (appcmd != 0 || mouse != HotkeyCmd::NONE)
      swprintf_s(line, 512, L"%s = %s, %s, %s, %s //%s\r\n",
        GetCmdNameByCmdCode(it->cmd).c_str(),
        GetKeyNameByKeyCode(key).c_str(),
        GetVirtNameByVirtCode(virt).c_str(),
        GetAppCmdNameByAppCmdCode(appcmd).c_str(),
        GetMouseNameByMouseCode(mouse).c_str(),
        (LPCTSTR)CString(MAKEINTRESOURCE(it->ids_cmd_comment)));
    else
      swprintf_s(line, 512, L"%s = %s, %s //%s\r\n",
        GetCmdNameByCmdCode(it->cmd).c_str(),
        GetKeyNameByKeyCode(key).c_str(),
        GetVirtNameByVirtCode(virt).c_str(),
        (LPCTSTR)CString(MAKEINTRESOURCE(it->ids_cmd_comment)));
    linefeeds.push_back(line);
  }

  // create file
  FILE* file = NULL;
  if (_wfopen_s(&file, filename, L"wb") != 0)
    return false;

  // write bom
  wchar_t bom = 0xfeff;
  if (fwrite(&bom, sizeof(bom), 1, file) != 1)
  {
    fclose(file);
    return false;
  }

  // write list
  for (std::vector<std::wstring>::iterator it = linefeeds.begin(); it != linefeeds.end(); it++)
  {
    if (fwrite(it->c_str(), it->length() * sizeof(wchar_t), 1, file) != 1)
    {
      fclose(file);
      return false;
    }
  }

  fclose(file);
  return true;
}

std::wstring HotkeySchemeParser::GetSchemeName()
{
  return m_schemename;
}

std::vector<HotkeyCmd> HotkeySchemeParser::GetScheme()
{
  return m_list;
}

#define CHKCMDNAME(x) if (cmdname == L#x) return x;
unsigned int HotkeySchemeParser::GetCmdCodeByCmdName(std::wstring cmdname)
{
  Strings::Trim(cmdname);
  CHKCMDNAME(ID_FILE_OPENMEDIA);
  CHKCMDNAME(ID_FILE_OPENDVD);
  CHKCMDNAME(ID_FILE_OPENDEVICE);
  CHKCMDNAME(ID_FILE_SAVE_COPY);
  CHKCMDNAME(ID_FILE_SAVE_IMAGE);
  CHKCMDNAME(ID_FILE_SAVE_IMAGE_AUTO);
  CHKCMDNAME(ID_FILE_LOAD_SUBTITLE);
  CHKCMDNAME(ID_FILE_SAVE_SUBTITLE);
  CHKCMDNAME(ID_FILE_PROPERTIES);
  CHKCMDNAME(ID_FILE_EXIT);
  CHKCMDNAME(ID_VIEW_CAPTIONMENU);
  CHKCMDNAME(ID_VIEW_SEEKER);
  CHKCMDNAME(ID_VIEW_CONTROLS);
  CHKCMDNAME(ID_VIEW_PLAYLIST);
  CHKCMDNAME(ID_VIEW_CAPTURE);
  CHKCMDNAME(ID_VIEW_SHADEREDITOR);
  CHKCMDNAME(ID_VIEW_PRESETS_MINIMAL);
  CHKCMDNAME(ID_VIEW_PRESETS_COMPACT);
  CHKCMDNAME(ID_VIEW_PRESETS_NORMAL);
  CHKCMDNAME(ID_VIEW_FULLSCREEN);
  CHKCMDNAME(ID_VIEW_FULLSCREEN_SECONDARY);
  CHKCMDNAME(ID_VIEW_ZOOM_50);
  CHKCMDNAME(ID_VIEW_ZOOM_100);
  CHKCMDNAME(ID_VIEW_ZOOM_200);
  CHKCMDNAME(ID_VIEW_VF_HALF);
  CHKCMDNAME(ID_VIEW_VF_NORMAL);
  CHKCMDNAME(ID_VIEW_VF_DOUBLE);
  CHKCMDNAME(ID_VIEW_VF_STRETCH);
  CHKCMDNAME(ID_VIEW_VF_FROMINSIDE);
  CHKCMDNAME(ID_VIEW_VF_FROMOUTSIDE);
  CHKCMDNAME(ID_ASPECTRATIO_NEXT);
  CHKCMDNAME(ID_VIEW_RESET);
  CHKCMDNAME(ID_VIEW_INCSIZE);
  CHKCMDNAME(ID_VIEW_DECSIZE);
  CHKCMDNAME(ID_VIEW_INCWIDTH);
  CHKCMDNAME(ID_VIEW_DECWIDTH);
  CHKCMDNAME(ID_VIEW_INCHEIGHT);
  CHKCMDNAME(ID_VIEW_DECHEIGHT);
  CHKCMDNAME(ID_PANSCAN_MOVELEFT);
  CHKCMDNAME(ID_PANSCAN_MOVERIGHT);
  CHKCMDNAME(ID_PANSCAN_MOVEUP);
  CHKCMDNAME(ID_PANSCAN_MOVEDOWN);
  CHKCMDNAME(ID_PANSCAN_MOVEUPLEFT);
  CHKCMDNAME(ID_PANSCAN_MOVEUPRIGHT);
  CHKCMDNAME(ID_PANSCAN_MOVEDOWNLEFT);
  CHKCMDNAME(ID_PANSCAN_MOVEDOWNRIGHT);
  CHKCMDNAME(ID_PANSCAN_CENTER);
  CHKCMDNAME(ID_PANSCAN_ROTATEXP);
  CHKCMDNAME(ID_PANSCAN_ROTATEXM);
  CHKCMDNAME(ID_PANSCAN_ROTATEYP);
  CHKCMDNAME(ID_PANSCAN_ROTATEYM);
  CHKCMDNAME(ID_PANSCAN_ROTATEZP);
  CHKCMDNAME(ID_PANSCAN_ROTATEZM);
  CHKCMDNAME(ID_ONTOP_ALWAYS);
  CHKCMDNAME(ID_VIEW_OPTIONS);
  CHKCMDNAME(ID_PLAY_PLAY);
  CHKCMDNAME(ID_PLAY_PAUSE);
  CHKCMDNAME(ID_PLAY_PLAYPAUSE);
  CHKCMDNAME(ID_PLAY_FRAMESTEP);
  CHKCMDNAME(ID_PLAY_FRAMESTEPCANCEL);
  CHKCMDNAME(ID_PLAY_GOTO);
  CHKCMDNAME(ID_PLAY_DECRATE);
  CHKCMDNAME(ID_PLAY_INCRATE);
  CHKCMDNAME(ID_PLAY_RESETRATE);
  CHKCMDNAME(ID_PLAY_SEEKKEYBACKWARD);
  CHKCMDNAME(ID_PLAY_SEEKKEYFORWARD);
  CHKCMDNAME(ID_PLAY_INCAUDDELAY);
  CHKCMDNAME(ID_PLAY_DECAUDDELAY);
  CHKCMDNAME(ID_VOLUME_UP);
  CHKCMDNAME(ID_VOLUME_DOWN);
  CHKCMDNAME(ID_VOLUME_MUTE);
  CHKCMDNAME(ID_NAVIGATE_SKIPBACKPLITEM);
  CHKCMDNAME(ID_NAVIGATE_SKIPFORWARDPLITEM);
  CHKCMDNAME(ID_NAVIGATE_SKIPBACK);
  CHKCMDNAME(ID_NAVIGATE_SKIPFORWARD);
  CHKCMDNAME(ID_NAVIGATE_TITLEMENU);
  CHKCMDNAME(ID_NAVIGATE_ROOTMENU);
  CHKCMDNAME(ID_NAVIGATE_SUBPICTUREMENU);
  CHKCMDNAME(ID_NAVIGATE_AUDIOMENU);
  CHKCMDNAME(ID_NAVIGATE_ANGLEMENU);
  CHKCMDNAME(ID_NAVIGATE_CHAPTERMENU);
  CHKCMDNAME(ID_NAVIGATE_MENU_LEFT);
  CHKCMDNAME(ID_NAVIGATE_MENU_RIGHT);
  CHKCMDNAME(ID_NAVIGATE_MENU_UP);
  CHKCMDNAME(ID_NAVIGATE_MENU_DOWN);
  CHKCMDNAME(ID_NAVIGATE_MENU_ACTIVATE);
  CHKCMDNAME(ID_NAVIGATE_MENU_BACK);
  CHKCMDNAME(ID_NAVIGATE_MENU_LEAVE);
  CHKCMDNAME(ID_BOSS);
  CHKCMDNAME(ID_MENU_PLAYER_SHORT);
  CHKCMDNAME(ID_STREAM_AUDIO_NEXT);
  CHKCMDNAME(ID_STREAM_AUDIO_PREV);
  CHKCMDNAME(ID_STREAM_SUB_NEXT);
  CHKCMDNAME(ID_STREAM_SUB_PREV);
  CHKCMDNAME(ID_STREAM_SUB_ONOFF);
  CHKCMDNAME(ID_OGM_AUDIO_NEXT);
  CHKCMDNAME(ID_OGM_AUDIO_PREV);
  CHKCMDNAME(ID_OGM_SUB_NEXT);
  CHKCMDNAME(ID_OGM_SUB_PREV);
  CHKCMDNAME(ID_DVD_ANGLE_NEXT);
  CHKCMDNAME(ID_DVD_ANGLE_PREV);
  CHKCMDNAME(ID_DVD_AUDIO_NEXT);
  CHKCMDNAME(ID_DVD_AUDIO_PREV);
  CHKCMDNAME(ID_DVD_SUB_NEXT);
  CHKCMDNAME(ID_DVD_SUB_PREV);
  CHKCMDNAME(ID_DVD_SUB_ONOFF);
  CHKCMDNAME(ID_VIEW_ZOOM_AUTOFIT);
  CHKCMDNAME(ID_FILE_OPENQUICK);
  CHKCMDNAME(ID_SUBMOVEUP);
  CHKCMDNAME(ID_SUBMOVEDOWN);
  CHKCMDNAME(ID_SUB2MOVEUP);
  CHKCMDNAME(ID_SUB2MOVEDOWN);
  CHKCMDNAME(ID_SUBFONTUPBOTH);
  CHKCMDNAME(ID_SUBFONTDOWNBOTH);
  CHKCMDNAME(ID_SUB1FONTUP);
  CHKCMDNAME(ID_SUB1FONTDOWN);
  CHKCMDNAME(ID_SUB2FONTUP);
  CHKCMDNAME(ID_SUB2FONTDOWN);
  CHKCMDNAME(ID_PLAY_SEEKBACKWARDSMALL);
  CHKCMDNAME(ID_PLAY_SEEKFORWARDSMALL);
  CHKCMDNAME(ID_PLAY_SEEKBACKWARDMED);
  CHKCMDNAME(ID_PLAY_SEEKFORWARDMED);
  CHKCMDNAME(ID_PLAY_SEEKBACKWARDLARGE);
  CHKCMDNAME(ID_PLAY_SEEKFORWARDLARGE);
  CHKCMDNAME(ID_FILE_OPENFOLDER);
  CHKCMDNAME(ID_FILE_OPENBDVD);
  CHKCMDNAME(ID_ABCONTROL_SETA);
  CHKCMDNAME(ID_ABCONTROL_SETB);
  CHKCMDNAME(ID_ABCONTROL_TOGGLE);
  CHKCMDNAME(ID_SHOWDRAWSTAT);
  CHKCMDNAME(ID_VSYNC_OFFSET_MORE);
  CHKCMDNAME(ID_VSYNC_OFFSET_LESS);
  CHKCMDNAME(ID_SWITCH_AUDIO_DEVICE);
  CHKCMDNAME(ID_SEEK_TO_BEGINNING);
  CHKCMDNAME(ID_SEEK_TO_MIDDLE);
  CHKCMDNAME(ID_SEEK_TO_END);
  CHKCMDNAME(ID_PLAY_MANUAL_STOP);
  CHKCMDNAME(ID_SUBTITLES_SUBITEM_RELOAD);
  CHKCMDNAME(ID_TOGGLE_SUBTITLE);
  CHKCMDNAME(ID_FILE_COPYTOCLIPBOARD);
  CHKCMDNAME(ID_PLAYLIST_DELETEITEM);
  CHKCMDNAME(ID_SHOW_VIDEO_STAT_OSD);
  CHKCMDNAME(ID_SUB_DELAY_DOWN);
  CHKCMDNAME(ID_SUB_DELAY_UP);
  CHKCMDNAME(ID_SUB_DELAY_DOWN2);
  CHKCMDNAME(ID_SUB_DELAY_UP2);
  CHKCMDNAME(ID_FILE_OPENURLSTREAM);
  CHKCMDNAME(ID_BRIGHTINC);
  CHKCMDNAME(ID_BRIGHTDEC);
  CHKCMDNAME(ID_SHOWTRANSPRANTBAR);
  return 0;
}
#undef CHKCMDNAME

#define CHKCMDCODE(x) case x: return L#x;
std::wstring HotkeySchemeParser::GetCmdNameByCmdCode(unsigned int cmdcode)
{
  switch (cmdcode)
  {
    CHKCMDCODE(ID_FILE_OPENMEDIA);
    CHKCMDCODE(ID_FILE_OPENDVD);
    CHKCMDCODE(ID_FILE_OPENDEVICE);
    CHKCMDCODE(ID_FILE_SAVE_COPY);
    CHKCMDCODE(ID_FILE_SAVE_IMAGE);
    CHKCMDCODE(ID_FILE_SAVE_IMAGE_AUTO);
    CHKCMDCODE(ID_FILE_LOAD_SUBTITLE);
    CHKCMDCODE(ID_FILE_SAVE_SUBTITLE);
    CHKCMDCODE(ID_FILE_PROPERTIES);
    CHKCMDCODE(ID_FILE_EXIT);
    CHKCMDCODE(ID_VIEW_CAPTIONMENU);
    CHKCMDCODE(ID_VIEW_SEEKER);
    CHKCMDCODE(ID_VIEW_CONTROLS);
    CHKCMDCODE(ID_VIEW_PLAYLIST);
    CHKCMDCODE(ID_VIEW_CAPTURE);
    CHKCMDCODE(ID_VIEW_SHADEREDITOR);
    CHKCMDCODE(ID_VIEW_PRESETS_MINIMAL);
    CHKCMDCODE(ID_VIEW_PRESETS_COMPACT);
    CHKCMDCODE(ID_VIEW_PRESETS_NORMAL);
    CHKCMDCODE(ID_VIEW_FULLSCREEN);
    CHKCMDCODE(ID_VIEW_FULLSCREEN_SECONDARY);
    CHKCMDCODE(ID_VIEW_ZOOM_50);
    CHKCMDCODE(ID_VIEW_ZOOM_100);
    CHKCMDCODE(ID_VIEW_ZOOM_200);
    CHKCMDCODE(ID_VIEW_VF_HALF);
    CHKCMDCODE(ID_VIEW_VF_NORMAL);
    CHKCMDCODE(ID_VIEW_VF_DOUBLE);
    CHKCMDCODE(ID_VIEW_VF_STRETCH);
    CHKCMDCODE(ID_VIEW_VF_FROMINSIDE);
    CHKCMDCODE(ID_VIEW_VF_FROMOUTSIDE);
    CHKCMDCODE(ID_ASPECTRATIO_NEXT);
    CHKCMDCODE(ID_VIEW_RESET);
    CHKCMDCODE(ID_VIEW_INCSIZE);
    CHKCMDCODE(ID_VIEW_DECSIZE);
    CHKCMDCODE(ID_VIEW_INCWIDTH);
    CHKCMDCODE(ID_VIEW_DECWIDTH);
    CHKCMDCODE(ID_VIEW_INCHEIGHT);
    CHKCMDCODE(ID_VIEW_DECHEIGHT);
    CHKCMDCODE(ID_PANSCAN_MOVELEFT);
    CHKCMDCODE(ID_PANSCAN_MOVERIGHT);
    CHKCMDCODE(ID_PANSCAN_MOVEUP);
    CHKCMDCODE(ID_PANSCAN_MOVEDOWN);
    CHKCMDCODE(ID_PANSCAN_MOVEUPLEFT);
    CHKCMDCODE(ID_PANSCAN_MOVEUPRIGHT);
    CHKCMDCODE(ID_PANSCAN_MOVEDOWNLEFT);
    CHKCMDCODE(ID_PANSCAN_MOVEDOWNRIGHT);
    CHKCMDCODE(ID_PANSCAN_CENTER);
    CHKCMDCODE(ID_PANSCAN_ROTATEXP);
    CHKCMDCODE(ID_PANSCAN_ROTATEXM);
    CHKCMDCODE(ID_PANSCAN_ROTATEYP);
    CHKCMDCODE(ID_PANSCAN_ROTATEYM);
    CHKCMDCODE(ID_PANSCAN_ROTATEZP);
    CHKCMDCODE(ID_PANSCAN_ROTATEZM);
    CHKCMDCODE(ID_ONTOP_ALWAYS);
    CHKCMDCODE(ID_VIEW_OPTIONS);
    CHKCMDCODE(ID_PLAY_PLAY);
    CHKCMDCODE(ID_PLAY_PAUSE);
    CHKCMDCODE(ID_PLAY_PLAYPAUSE);
    CHKCMDCODE(ID_PLAY_FRAMESTEP);
    CHKCMDCODE(ID_PLAY_FRAMESTEPCANCEL);
    CHKCMDCODE(ID_PLAY_GOTO);
    CHKCMDCODE(ID_PLAY_DECRATE);
    CHKCMDCODE(ID_PLAY_INCRATE);
    CHKCMDCODE(ID_PLAY_RESETRATE);
    CHKCMDCODE(ID_PLAY_SEEKKEYBACKWARD);
    CHKCMDCODE(ID_PLAY_SEEKKEYFORWARD);
    CHKCMDCODE(ID_PLAY_INCAUDDELAY);
    CHKCMDCODE(ID_PLAY_DECAUDDELAY);
    CHKCMDCODE(ID_VOLUME_UP);
    CHKCMDCODE(ID_VOLUME_DOWN);
    CHKCMDCODE(ID_VOLUME_MUTE);
    CHKCMDCODE(ID_NAVIGATE_SKIPBACKPLITEM);
    CHKCMDCODE(ID_NAVIGATE_SKIPFORWARDPLITEM);
    CHKCMDCODE(ID_NAVIGATE_SKIPBACK);
    CHKCMDCODE(ID_NAVIGATE_SKIPFORWARD);
    CHKCMDCODE(ID_NAVIGATE_TITLEMENU);
    CHKCMDCODE(ID_NAVIGATE_ROOTMENU);
    CHKCMDCODE(ID_NAVIGATE_SUBPICTUREMENU);
    CHKCMDCODE(ID_NAVIGATE_AUDIOMENU);
    CHKCMDCODE(ID_NAVIGATE_ANGLEMENU);
    CHKCMDCODE(ID_NAVIGATE_CHAPTERMENU);
    CHKCMDCODE(ID_NAVIGATE_MENU_LEFT);
    CHKCMDCODE(ID_NAVIGATE_MENU_RIGHT);
    CHKCMDCODE(ID_NAVIGATE_MENU_UP);
    CHKCMDCODE(ID_NAVIGATE_MENU_DOWN);
    CHKCMDCODE(ID_NAVIGATE_MENU_ACTIVATE);
    CHKCMDCODE(ID_NAVIGATE_MENU_BACK);
    CHKCMDCODE(ID_NAVIGATE_MENU_LEAVE);
    CHKCMDCODE(ID_BOSS);
    CHKCMDCODE(ID_MENU_PLAYER_SHORT);
    CHKCMDCODE(ID_STREAM_AUDIO_NEXT);
    CHKCMDCODE(ID_STREAM_AUDIO_PREV);
    CHKCMDCODE(ID_STREAM_SUB_NEXT);
    CHKCMDCODE(ID_STREAM_SUB_PREV);
    CHKCMDCODE(ID_STREAM_SUB_ONOFF);
    CHKCMDCODE(ID_OGM_AUDIO_NEXT);
    CHKCMDCODE(ID_OGM_AUDIO_PREV);
    CHKCMDCODE(ID_OGM_SUB_NEXT);
    CHKCMDCODE(ID_OGM_SUB_PREV);
    CHKCMDCODE(ID_DVD_ANGLE_NEXT);
    CHKCMDCODE(ID_DVD_ANGLE_PREV);
    CHKCMDCODE(ID_DVD_AUDIO_NEXT);
    CHKCMDCODE(ID_DVD_AUDIO_PREV);
    CHKCMDCODE(ID_DVD_SUB_NEXT);
    CHKCMDCODE(ID_DVD_SUB_PREV);
    CHKCMDCODE(ID_DVD_SUB_ONOFF);
    CHKCMDCODE(ID_VIEW_ZOOM_AUTOFIT);
    CHKCMDCODE(ID_FILE_OPENQUICK);
    CHKCMDCODE(ID_SUBMOVEUP);
    CHKCMDCODE(ID_SUBMOVEDOWN);
    CHKCMDCODE(ID_SUB2MOVEUP);
    CHKCMDCODE(ID_SUB2MOVEDOWN);
    CHKCMDCODE(ID_SUBFONTUPBOTH);
    CHKCMDCODE(ID_SUBFONTDOWNBOTH);
    CHKCMDCODE(ID_SUB1FONTUP);
    CHKCMDCODE(ID_SUB1FONTDOWN);
    CHKCMDCODE(ID_SUB2FONTUP);
    CHKCMDCODE(ID_SUB2FONTDOWN);
    CHKCMDCODE(ID_PLAY_SEEKBACKWARDSMALL);
    CHKCMDCODE(ID_PLAY_SEEKFORWARDSMALL);
    CHKCMDCODE(ID_PLAY_SEEKBACKWARDMED);
    CHKCMDCODE(ID_PLAY_SEEKFORWARDMED);
    CHKCMDCODE(ID_PLAY_SEEKBACKWARDLARGE);
    CHKCMDCODE(ID_PLAY_SEEKFORWARDLARGE);
    CHKCMDCODE(ID_FILE_OPENFOLDER);
    CHKCMDCODE(ID_FILE_OPENBDVD);
    CHKCMDCODE(ID_ABCONTROL_SETA);
    CHKCMDCODE(ID_ABCONTROL_SETB);
    CHKCMDCODE(ID_ABCONTROL_TOGGLE);
    CHKCMDCODE(ID_SHOWDRAWSTAT);
    CHKCMDCODE(ID_VSYNC_OFFSET_MORE);
    CHKCMDCODE(ID_VSYNC_OFFSET_LESS);
    CHKCMDCODE(ID_SWITCH_AUDIO_DEVICE);
    CHKCMDCODE(ID_SEEK_TO_BEGINNING);
    CHKCMDCODE(ID_SEEK_TO_MIDDLE);
    CHKCMDCODE(ID_SEEK_TO_END);
    CHKCMDCODE(ID_PLAY_MANUAL_STOP);
    CHKCMDCODE(ID_SUBTITLES_SUBITEM_RELOAD);
    CHKCMDCODE(ID_TOGGLE_SUBTITLE);
    CHKCMDCODE(ID_FILE_COPYTOCLIPBOARD);
    CHKCMDCODE(ID_PLAYLIST_DELETEITEM);
    CHKCMDCODE(ID_SHOW_VIDEO_STAT_OSD);
    CHKCMDCODE(ID_SUB_DELAY_DOWN);
    CHKCMDCODE(ID_SUB_DELAY_UP);
    CHKCMDCODE(ID_SUB_DELAY_DOWN2);
    CHKCMDCODE(ID_SUB_DELAY_UP2);
    CHKCMDCODE(ID_FILE_OPENURLSTREAM);
    CHKCMDCODE(ID_BRIGHTINC);
    CHKCMDCODE(ID_BRIGHTDEC);
    CHKCMDCODE(ID_SHOWTRANSPRANTBAR);
  default:
    return L"CMD_NONE";
  }
}
#undef CHKCMDCODE(x)

#define CHKKEYCODE(x) case x: return L#x;
std::wstring HotkeySchemeParser::GetKeyNameByKeyCode(unsigned int keycode)
{
  if ((keycode >= 0x30 && keycode <= 0x39)
      || (keycode >= 0x41 && keycode <= 0x5A))
  {
    std::wstring vk_tpl = L"VK__";
    vk_tpl[3] = keycode;
    return vk_tpl;
  }
  switch (keycode)
  {
    CHKKEYCODE(VK_LBUTTON);
    CHKKEYCODE(VK_RBUTTON);
    CHKKEYCODE(VK_CANCEL);
    CHKKEYCODE(VK_MBUTTON);
    CHKKEYCODE(VK_XBUTTON1);
    CHKKEYCODE(VK_XBUTTON2);
    CHKKEYCODE(VK_BACK);
    CHKKEYCODE(VK_TAB);
    CHKKEYCODE(VK_CLEAR);
    CHKKEYCODE(VK_RETURN);
    CHKKEYCODE(VK_SHIFT);
    CHKKEYCODE(VK_CONTROL);
    CHKKEYCODE(VK_MENU);
    CHKKEYCODE(VK_PAUSE);
    CHKKEYCODE(VK_CAPITAL);
    CHKKEYCODE(VK_KANA);
    CHKKEYCODE(VK_JUNJA);
    CHKKEYCODE(VK_FINAL);
    CHKKEYCODE(VK_KANJI);
    CHKKEYCODE(VK_ESCAPE);
    CHKKEYCODE(VK_CONVERT);
    CHKKEYCODE(VK_NONCONVERT);
    CHKKEYCODE(VK_ACCEPT);
    CHKKEYCODE(VK_MODECHANGE);
    CHKKEYCODE(VK_SPACE);
    CHKKEYCODE(VK_PRIOR);
    CHKKEYCODE(VK_NEXT);
    CHKKEYCODE(VK_END);
    CHKKEYCODE(VK_HOME);
    CHKKEYCODE(VK_LEFT);
    CHKKEYCODE(VK_UP);
    CHKKEYCODE(VK_RIGHT);
    CHKKEYCODE(VK_DOWN);
    CHKKEYCODE(VK_SELECT);
    CHKKEYCODE(VK_PRINT);
    CHKKEYCODE(VK_EXECUTE);
    CHKKEYCODE(VK_SNAPSHOT);
    CHKKEYCODE(VK_INSERT);
    CHKKEYCODE(VK_DELETE);
    CHKKEYCODE(VK_HELP);
    CHKKEYCODE(VK_LWIN);
    CHKKEYCODE(VK_RWIN);
    CHKKEYCODE(VK_APPS);
    CHKKEYCODE(VK_SLEEP);
    CHKKEYCODE(VK_NUMPAD0);
    CHKKEYCODE(VK_NUMPAD1);
    CHKKEYCODE(VK_NUMPAD2);
    CHKKEYCODE(VK_NUMPAD3);
    CHKKEYCODE(VK_NUMPAD4);
    CHKKEYCODE(VK_NUMPAD5);
    CHKKEYCODE(VK_NUMPAD6);
    CHKKEYCODE(VK_NUMPAD7);
    CHKKEYCODE(VK_NUMPAD8);
    CHKKEYCODE(VK_NUMPAD9);
    CHKKEYCODE(VK_MULTIPLY);
    CHKKEYCODE(VK_ADD);
    CHKKEYCODE(VK_SEPARATOR);
    CHKKEYCODE(VK_SUBTRACT);
    CHKKEYCODE(VK_DECIMAL);
    CHKKEYCODE(VK_DIVIDE);
    CHKKEYCODE(VK_F1);
    CHKKEYCODE(VK_F2);
    CHKKEYCODE(VK_F3);
    CHKKEYCODE(VK_F4);
    CHKKEYCODE(VK_F5);
    CHKKEYCODE(VK_F6);
    CHKKEYCODE(VK_F7);
    CHKKEYCODE(VK_F8);
    CHKKEYCODE(VK_F9);
    CHKKEYCODE(VK_F10);
    CHKKEYCODE(VK_F11);
    CHKKEYCODE(VK_F12);
    CHKKEYCODE(VK_F13);
    CHKKEYCODE(VK_F14);
    CHKKEYCODE(VK_F15);
    CHKKEYCODE(VK_F16);
    CHKKEYCODE(VK_F17);
    CHKKEYCODE(VK_F18);
    CHKKEYCODE(VK_F19);
    CHKKEYCODE(VK_F20);
    CHKKEYCODE(VK_F21);
    CHKKEYCODE(VK_F22);
    CHKKEYCODE(VK_F23);
    CHKKEYCODE(VK_F24);
    CHKKEYCODE(VK_NUMLOCK);
    CHKKEYCODE(VK_SCROLL);
    CHKKEYCODE(VK_OEM_FJ_JISHO);
    CHKKEYCODE(VK_OEM_FJ_MASSHOU);
    CHKKEYCODE(VK_OEM_FJ_TOUROKU);
    CHKKEYCODE(VK_OEM_FJ_LOYA);
    CHKKEYCODE(VK_OEM_FJ_ROYA);
    CHKKEYCODE(VK_LSHIFT);
    CHKKEYCODE(VK_RSHIFT);
    CHKKEYCODE(VK_LCONTROL);
    CHKKEYCODE(VK_RCONTROL);
    CHKKEYCODE(VK_LMENU);
    CHKKEYCODE(VK_RMENU);
    CHKKEYCODE(VK_BROWSER_BACK);
    CHKKEYCODE(VK_BROWSER_FORWARD);
    CHKKEYCODE(VK_BROWSER_REFRESH);
    CHKKEYCODE(VK_BROWSER_STOP);
    CHKKEYCODE(VK_BROWSER_SEARCH);
    CHKKEYCODE(VK_BROWSER_FAVORITES);
    CHKKEYCODE(VK_BROWSER_HOME);
    CHKKEYCODE(VK_VOLUME_MUTE);
    CHKKEYCODE(VK_VOLUME_DOWN);
    CHKKEYCODE(VK_VOLUME_UP);
    CHKKEYCODE(VK_MEDIA_NEXT_TRACK);
    CHKKEYCODE(VK_MEDIA_PREV_TRACK);
    CHKKEYCODE(VK_MEDIA_STOP);
    CHKKEYCODE(VK_MEDIA_PLAY_PAUSE);
    CHKKEYCODE(VK_LAUNCH_MAIL);
    CHKKEYCODE(VK_LAUNCH_MEDIA_SELECT);
    CHKKEYCODE(VK_LAUNCH_APP1);
    CHKKEYCODE(VK_LAUNCH_APP2);
    CHKKEYCODE(VK_OEM_1);
    CHKKEYCODE(VK_OEM_PLUS);
    CHKKEYCODE(VK_OEM_COMMA);
    CHKKEYCODE(VK_OEM_MINUS);
    CHKKEYCODE(VK_OEM_PERIOD);
    CHKKEYCODE(VK_OEM_2);
    CHKKEYCODE(VK_OEM_3);
    CHKKEYCODE(VK_OEM_4);
    CHKKEYCODE(VK_OEM_5);
    CHKKEYCODE(VK_OEM_6);
    CHKKEYCODE(VK_OEM_7);
    CHKKEYCODE(VK_OEM_8);
    CHKKEYCODE(VK_OEM_AX);
    CHKKEYCODE(VK_OEM_102);
    CHKKEYCODE(VK_ICO_HELP);
    CHKKEYCODE(VK_ICO_00);
    CHKKEYCODE(VK_PROCESSKEY);
    CHKKEYCODE(VK_ICO_CLEAR);
    CHKKEYCODE(VK_PACKET);
    CHKKEYCODE(VK_OEM_RESET);
    CHKKEYCODE(VK_OEM_JUMP);
    CHKKEYCODE(VK_OEM_PA1);
    CHKKEYCODE(VK_OEM_PA2);
    CHKKEYCODE(VK_OEM_PA3);
    CHKKEYCODE(VK_OEM_WSCTRL);
    CHKKEYCODE(VK_OEM_CUSEL);
    CHKKEYCODE(VK_OEM_ATTN);
    CHKKEYCODE(VK_OEM_FINISH);
    CHKKEYCODE(VK_OEM_COPY);
    CHKKEYCODE(VK_OEM_AUTO);
    CHKKEYCODE(VK_OEM_ENLW);
    CHKKEYCODE(VK_OEM_BACKTAB);
    CHKKEYCODE(VK_ATTN);
    CHKKEYCODE(VK_CRSEL);
    CHKKEYCODE(VK_EXSEL);
    CHKKEYCODE(VK_EREOF);
    CHKKEYCODE(VK_PLAY);
    CHKKEYCODE(VK_ZOOM);
    CHKKEYCODE(VK_NONAME);
    CHKKEYCODE(VK_PA1);
  default:
    return L"KEY_NONE";
  }
}
#undef CHKKEYCODE

#define CHKKEYNAME(x) if (keyname == L#x) return x;
unsigned int HotkeySchemeParser::GetKeyCodeByKeyName(std::wstring keyname)
{
  Strings::Trim(keyname);
  if (keyname.length() == 4)
  {
    if (keyname.find(L"VK_") == 0)
    {
      wchar_t keytail = keyname[3];
      if (keytail >= L'0' && keytail <= L'9')
        return keytail;
      else if (keytail >= L'A' && keytail <= L'Z')
        return keytail;
    }
  }
  CHKKEYNAME(VK_LBUTTON);
  CHKKEYNAME(VK_RBUTTON);
  CHKKEYNAME(VK_CANCEL);
  CHKKEYNAME(VK_MBUTTON);
  CHKKEYNAME(VK_XBUTTON1);
  CHKKEYNAME(VK_XBUTTON2);
  CHKKEYNAME(VK_BACK);
  CHKKEYNAME(VK_TAB);
  CHKKEYNAME(VK_CLEAR);
  CHKKEYNAME(VK_RETURN);
  CHKKEYNAME(VK_SHIFT);
  CHKKEYNAME(VK_CONTROL);
  CHKKEYNAME(VK_MENU);
  CHKKEYNAME(VK_PAUSE);
  CHKKEYNAME(VK_CAPITAL);
  CHKKEYNAME(VK_KANA);
  CHKKEYNAME(VK_JUNJA);
  CHKKEYNAME(VK_FINAL);
  CHKKEYNAME(VK_HANJA);
  CHKKEYNAME(VK_KANJI);
  CHKKEYNAME(VK_ESCAPE);
  CHKKEYNAME(VK_CONVERT);
  CHKKEYNAME(VK_NONCONVERT);
  CHKKEYNAME(VK_ACCEPT);
  CHKKEYNAME(VK_MODECHANGE);
  CHKKEYNAME(VK_SPACE);
  CHKKEYNAME(VK_PRIOR);
  CHKKEYNAME(VK_NEXT);
  CHKKEYNAME(VK_END);
  CHKKEYNAME(VK_HOME);
  CHKKEYNAME(VK_LEFT);
  CHKKEYNAME(VK_UP);
  CHKKEYNAME(VK_RIGHT);
  CHKKEYNAME(VK_DOWN);
  CHKKEYNAME(VK_SELECT);
  CHKKEYNAME(VK_PRINT);
  CHKKEYNAME(VK_EXECUTE);
  CHKKEYNAME(VK_SNAPSHOT);
  CHKKEYNAME(VK_INSERT);
  CHKKEYNAME(VK_DELETE);
  CHKKEYNAME(VK_HELP);
  CHKKEYNAME(VK_LWIN);
  CHKKEYNAME(VK_RWIN);
  CHKKEYNAME(VK_APPS);
  CHKKEYNAME(VK_SLEEP);
  CHKKEYNAME(VK_NUMPAD0);
  CHKKEYNAME(VK_NUMPAD1);
  CHKKEYNAME(VK_NUMPAD2);
  CHKKEYNAME(VK_NUMPAD3);
  CHKKEYNAME(VK_NUMPAD4);
  CHKKEYNAME(VK_NUMPAD5);
  CHKKEYNAME(VK_NUMPAD6);
  CHKKEYNAME(VK_NUMPAD7);
  CHKKEYNAME(VK_NUMPAD8);
  CHKKEYNAME(VK_NUMPAD9);
  CHKKEYNAME(VK_MULTIPLY);
  CHKKEYNAME(VK_ADD);
  CHKKEYNAME(VK_SEPARATOR);
  CHKKEYNAME(VK_SUBTRACT);
  CHKKEYNAME(VK_DECIMAL);
  CHKKEYNAME(VK_DIVIDE);
  CHKKEYNAME(VK_F1);
  CHKKEYNAME(VK_F2);
  CHKKEYNAME(VK_F3);
  CHKKEYNAME(VK_F4);
  CHKKEYNAME(VK_F5);
  CHKKEYNAME(VK_F6);
  CHKKEYNAME(VK_F7);
  CHKKEYNAME(VK_F8);
  CHKKEYNAME(VK_F9);
  CHKKEYNAME(VK_F10);
  CHKKEYNAME(VK_F11);
  CHKKEYNAME(VK_F12);
  CHKKEYNAME(VK_F13);
  CHKKEYNAME(VK_F14);
  CHKKEYNAME(VK_F15);
  CHKKEYNAME(VK_F16);
  CHKKEYNAME(VK_F17);
  CHKKEYNAME(VK_F18);
  CHKKEYNAME(VK_F19);
  CHKKEYNAME(VK_F20);
  CHKKEYNAME(VK_F21);
  CHKKEYNAME(VK_F22);
  CHKKEYNAME(VK_F23);
  CHKKEYNAME(VK_F24);
  CHKKEYNAME(VK_NUMLOCK);
  CHKKEYNAME(VK_SCROLL);
  CHKKEYNAME(VK_OEM_NEC_EQUAL);
  CHKKEYNAME(VK_OEM_FJ_JISHO);
  CHKKEYNAME(VK_OEM_FJ_MASSHOU);
  CHKKEYNAME(VK_OEM_FJ_TOUROKU);
  CHKKEYNAME(VK_OEM_FJ_LOYA);
  CHKKEYNAME(VK_OEM_FJ_ROYA);
  CHKKEYNAME(VK_LSHIFT);
  CHKKEYNAME(VK_RSHIFT);
  CHKKEYNAME(VK_LCONTROL);
  CHKKEYNAME(VK_RCONTROL);
  CHKKEYNAME(VK_LMENU);
  CHKKEYNAME(VK_RMENU);
  CHKKEYNAME(VK_BROWSER_BACK);
  CHKKEYNAME(VK_BROWSER_FORWARD);
  CHKKEYNAME(VK_BROWSER_REFRESH);
  CHKKEYNAME(VK_BROWSER_STOP);
  CHKKEYNAME(VK_BROWSER_SEARCH);
  CHKKEYNAME(VK_BROWSER_FAVORITES);
  CHKKEYNAME(VK_BROWSER_HOME);
  CHKKEYNAME(VK_VOLUME_MUTE);
  CHKKEYNAME(VK_VOLUME_DOWN);
  CHKKEYNAME(VK_VOLUME_UP);
  CHKKEYNAME(VK_MEDIA_NEXT_TRACK);
  CHKKEYNAME(VK_MEDIA_PREV_TRACK);
  CHKKEYNAME(VK_MEDIA_STOP);
  CHKKEYNAME(VK_MEDIA_PLAY_PAUSE);
  CHKKEYNAME(VK_LAUNCH_MAIL);
  CHKKEYNAME(VK_LAUNCH_MEDIA_SELECT);
  CHKKEYNAME(VK_LAUNCH_APP1);
  CHKKEYNAME(VK_LAUNCH_APP2);
  CHKKEYNAME(VK_OEM_1);
  CHKKEYNAME(VK_OEM_PLUS);
  CHKKEYNAME(VK_OEM_COMMA);
  CHKKEYNAME(VK_OEM_MINUS);
  CHKKEYNAME(VK_OEM_PERIOD);
  CHKKEYNAME(VK_OEM_2);
  CHKKEYNAME(VK_OEM_3);
  CHKKEYNAME(VK_OEM_4);
  CHKKEYNAME(VK_OEM_5);
  CHKKEYNAME(VK_OEM_6);
  CHKKEYNAME(VK_OEM_7);
  CHKKEYNAME(VK_OEM_8);
  CHKKEYNAME(VK_OEM_AX);
  CHKKEYNAME(VK_OEM_102);
  CHKKEYNAME(VK_ICO_HELP);
  CHKKEYNAME(VK_ICO_00);
  CHKKEYNAME(VK_PROCESSKEY);
  CHKKEYNAME(VK_ICO_CLEAR);
  CHKKEYNAME(VK_PACKET);
  CHKKEYNAME(VK_OEM_RESET);
  CHKKEYNAME(VK_OEM_JUMP);
  CHKKEYNAME(VK_OEM_PA1);
  CHKKEYNAME(VK_OEM_PA2);
  CHKKEYNAME(VK_OEM_PA3);
  CHKKEYNAME(VK_OEM_WSCTRL);
  CHKKEYNAME(VK_OEM_CUSEL);
  CHKKEYNAME(VK_OEM_ATTN);
  CHKKEYNAME(VK_OEM_FINISH);
  CHKKEYNAME(VK_OEM_COPY);
  CHKKEYNAME(VK_OEM_AUTO);
  CHKKEYNAME(VK_OEM_ENLW);
  CHKKEYNAME(VK_OEM_BACKTAB);
  CHKKEYNAME(VK_ATTN);
  CHKKEYNAME(VK_CRSEL);
  CHKKEYNAME(VK_EXSEL);
  CHKKEYNAME(VK_EREOF);
  CHKKEYNAME(VK_PLAY);
  CHKKEYNAME(VK_ZOOM);
  CHKKEYNAME(VK_NONAME);
  CHKKEYNAME(VK_PA1);
  return 0;
}
#undef CHKKEYNAME

std::wstring HotkeySchemeParser::GetMouseNameByMouseCode(unsigned int mousecode)
{
  switch (mousecode)
  {
  case HotkeyCmd::NONE:
    return L"NONE";
  case HotkeyCmd::LDOWN:
    return L"LDOWN";
  case HotkeyCmd::LUP:
    return L"LUP";
  case HotkeyCmd::LDBLCLK:
    return L"LDBLCLK";
  case HotkeyCmd::MDOWN:
    return L"MDOWN";
  case HotkeyCmd::MUP:
    return L"MUP";
  case HotkeyCmd::MDBLCLK:
    return L"MDBLCLK";
  case HotkeyCmd::RDOWN:
    return L"RDOWN";
  case HotkeyCmd::RUP:
    return L"RUP";
  case HotkeyCmd::RDBLCLK:
    return L"RDBLCLK";
  case HotkeyCmd::X1DOWN:
    return L"X1DOWN";
  case HotkeyCmd::X1UP:
    return L"X1UP";
  case HotkeyCmd::X1DBLCLK:
    return L"X1DBLCLK";
  case HotkeyCmd::X2DOWN:
    return L"X2DOWN";
  case HotkeyCmd::X2UP:
    return L"X2UP";
  case HotkeyCmd::X2DBLCLK:
    return L"X2DBLCLK";
  case HotkeyCmd::WUP:
    return L"WUP";
  case HotkeyCmd::WDOWN:
    return L"WDOWN";
  default:
    return L"MOUSE_ERROR";
  }
}

unsigned int HotkeySchemeParser::GetMouseCodeByMouseName(std::wstring mousename)
{
  Strings::Trim(mousename);
  if (mousename == L"NONE")
    return HotkeyCmd::NONE;
  if (mousename == L"LDOWN")
    return HotkeyCmd::LDOWN;
  if (mousename == L"LUP")
    return HotkeyCmd::LUP;
  if (mousename == L"LDBLCLK")
    return HotkeyCmd::LDBLCLK;
  if (mousename == L"MDOWN")
    return HotkeyCmd::MDOWN;
  if (mousename == L"MUP")
    return HotkeyCmd::MUP;
  if (mousename == L"MDBLCLK")
    return HotkeyCmd::MDBLCLK;
  if (mousename == L"RDOWN")
    return HotkeyCmd::RDOWN;
  if (mousename == L"RUP")
    return HotkeyCmd::RUP;
  if (mousename == L"RDBLCLK")
    return HotkeyCmd::RDBLCLK;
  if (mousename == L"X1DOWN")
    return HotkeyCmd::X1DOWN;
  if (mousename == L"X1UP")
    return HotkeyCmd::X1UP;
  if (mousename == L"X1DBLCLK")
    return HotkeyCmd::X1DBLCLK;
  if (mousename == L"X2DOWN")
    return HotkeyCmd::X2DOWN;
  if (mousename == L"X2UP")
    return HotkeyCmd::X2UP;
  if (mousename == L"X2DBLCLK")
    return HotkeyCmd::X2DBLCLK;
  if (mousename == L"WUP")
    return HotkeyCmd::WUP;
  if (mousename == L"WDOWN")
    return HotkeyCmd::WDOWN;
  return 0;
}

std::wstring HotkeySchemeParser::GetVirtNameByVirtCode(unsigned int virtcode)
{
  std::wstring virtname = L"";
  int bitindex = 0;
  while (virtcode > 0)
  {
    bitindex++;
    bool flag = virtcode % 2;
    virtcode >>= 1;
    if (flag)
    {
      switch (bitindex)
      {
      case 1:
        virtname.append(virtname == L"" ? L"FVIRTKEY" : L"|FVIRTKEY");
        break;
      case 2:
        virtname.append(virtname == L"" ? L"FNOINVERT" : L"|FNOINVERT");
        break;
      case 3:
        virtname.append(virtname == L"" ? L"FSHIFT" : L"|FSHIFT");
        break;
      case 4:
        virtname.append(virtname == L"" ? L"FCONTROL" : L"|FCONTROL");
        break;
      case 5:
        virtname.append(virtname == L"" ? L"FALT" : L"|FALT");
        break;
      }
    }
  }
  return virtname;
}

unsigned int HotkeySchemeParser::GetVirtCodeByVirtName(std::wstring virtname)
{
  Strings::Trim(virtname);
  int virtcode = 0;

  if (virtname.find(L"FVIRTKEY") != virtname.npos)
    virtcode |= FVIRTKEY;
  if (virtname.find(L"FNOINVERT") != virtname.npos)
    virtcode |= FNOINVERT;
  if (virtname.find(L"FSHIFT") != virtname.npos)
    virtcode |= FSHIFT;
  if (virtname.find(L"FCONTROL") != virtname.npos)
    virtcode |= FCONTROL;
  if (virtname.find(L"FALT") != virtname.npos)
    virtcode |= FALT;
  
  return virtcode;
}

#define CHKAPPCMDNAME(x) if (appcmdname == L#x) return x;
unsigned int HotkeySchemeParser::GetAppCmdCodeByAppCmdName(std::wstring appcmdname)
{
  Strings::Trim(appcmdname);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_BACKWARD);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_FORWARD);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_REFRESH);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_STOP);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_SEARCH);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_FAVORITES);
  CHKAPPCMDNAME(APPCOMMAND_BROWSER_HOME);
  CHKAPPCMDNAME(APPCOMMAND_VOLUME_MUTE);
  CHKAPPCMDNAME(APPCOMMAND_VOLUME_DOWN);
  CHKAPPCMDNAME(APPCOMMAND_VOLUME_UP);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_NEXTTRACK);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_PREVIOUSTRACK);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_STOP);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_PLAY_PAUSE);
  CHKAPPCMDNAME(APPCOMMAND_LAUNCH_MAIL);
  CHKAPPCMDNAME(APPCOMMAND_LAUNCH_MEDIA_SELECT);
  CHKAPPCMDNAME(APPCOMMAND_LAUNCH_APP1);
  CHKAPPCMDNAME(APPCOMMAND_LAUNCH_APP2);
  CHKAPPCMDNAME(APPCOMMAND_BASS_DOWN);
  CHKAPPCMDNAME(APPCOMMAND_BASS_BOOST);
  CHKAPPCMDNAME(APPCOMMAND_BASS_UP);
  CHKAPPCMDNAME(APPCOMMAND_TREBLE_DOWN);
  CHKAPPCMDNAME(APPCOMMAND_TREBLE_UP);
  CHKAPPCMDNAME(APPCOMMAND_MICROPHONE_VOLUME_MUTE);
  CHKAPPCMDNAME(APPCOMMAND_MICROPHONE_VOLUME_DOWN);
  CHKAPPCMDNAME(APPCOMMAND_MICROPHONE_VOLUME_UP);
  CHKAPPCMDNAME(APPCOMMAND_HELP);
  CHKAPPCMDNAME(APPCOMMAND_FIND);
  CHKAPPCMDNAME(APPCOMMAND_NEW);
  CHKAPPCMDNAME(APPCOMMAND_OPEN);
  CHKAPPCMDNAME(APPCOMMAND_CLOSE);
  CHKAPPCMDNAME(APPCOMMAND_SAVE);
  CHKAPPCMDNAME(APPCOMMAND_PRINT);
  CHKAPPCMDNAME(APPCOMMAND_UNDO);
  CHKAPPCMDNAME(APPCOMMAND_REDO);
  CHKAPPCMDNAME(APPCOMMAND_COPY);
  CHKAPPCMDNAME(APPCOMMAND_CUT);
  CHKAPPCMDNAME(APPCOMMAND_PASTE);
  CHKAPPCMDNAME(APPCOMMAND_REPLY_TO_MAIL);
  CHKAPPCMDNAME(APPCOMMAND_FORWARD_MAIL);
  CHKAPPCMDNAME(APPCOMMAND_SEND_MAIL);
  CHKAPPCMDNAME(APPCOMMAND_SPELL_CHECK);
  CHKAPPCMDNAME(APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE);
  CHKAPPCMDNAME(APPCOMMAND_MIC_ON_OFF_TOGGLE);
  CHKAPPCMDNAME(APPCOMMAND_CORRECTION_LIST);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_PLAY);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_PAUSE);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_RECORD);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_FAST_FORWARD);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_REWIND);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_CHANNEL_UP);
  CHKAPPCMDNAME(APPCOMMAND_MEDIA_CHANNEL_DOWN);
  CHKAPPCMDNAME(APPCOMMAND_DELETE);
  return 0;
}
#undef CHKAPPCMDNAME

#define CHKAPPCMDCODE(x) case x: return L#x; 
std::wstring HotkeySchemeParser::GetAppCmdNameByAppCmdCode(unsigned int appcmdcode)
{
  switch (appcmdcode)
  {
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_BACKWARD)
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_FORWARD);
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_REFRESH);
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_STOP);
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_SEARCH);
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_FAVORITES);
  CHKAPPCMDCODE(APPCOMMAND_BROWSER_HOME);
  CHKAPPCMDCODE(APPCOMMAND_VOLUME_MUTE);
  CHKAPPCMDCODE(APPCOMMAND_VOLUME_DOWN);
  CHKAPPCMDCODE(APPCOMMAND_VOLUME_UP);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_NEXTTRACK);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_PREVIOUSTRACK);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_STOP);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_PLAY_PAUSE);
  CHKAPPCMDCODE(APPCOMMAND_LAUNCH_MAIL);
  CHKAPPCMDCODE(APPCOMMAND_LAUNCH_MEDIA_SELECT);
  CHKAPPCMDCODE(APPCOMMAND_LAUNCH_APP1);
  CHKAPPCMDCODE(APPCOMMAND_LAUNCH_APP2);
  CHKAPPCMDCODE(APPCOMMAND_BASS_DOWN);
  CHKAPPCMDCODE(APPCOMMAND_BASS_BOOST);
  CHKAPPCMDCODE(APPCOMMAND_BASS_UP);
  CHKAPPCMDCODE(APPCOMMAND_TREBLE_DOWN);
  CHKAPPCMDCODE(APPCOMMAND_TREBLE_UP);
  CHKAPPCMDCODE(APPCOMMAND_MICROPHONE_VOLUME_MUTE);
  CHKAPPCMDCODE(APPCOMMAND_MICROPHONE_VOLUME_DOWN);
  CHKAPPCMDCODE(APPCOMMAND_MICROPHONE_VOLUME_UP);
  CHKAPPCMDCODE(APPCOMMAND_HELP);
  CHKAPPCMDCODE(APPCOMMAND_FIND);
  CHKAPPCMDCODE(APPCOMMAND_NEW);
  CHKAPPCMDCODE(APPCOMMAND_OPEN);
  CHKAPPCMDCODE(APPCOMMAND_CLOSE);
  CHKAPPCMDCODE(APPCOMMAND_SAVE);
  CHKAPPCMDCODE(APPCOMMAND_PRINT);
  CHKAPPCMDCODE(APPCOMMAND_UNDO);
  CHKAPPCMDCODE(APPCOMMAND_REDO);
  CHKAPPCMDCODE(APPCOMMAND_COPY);
  CHKAPPCMDCODE(APPCOMMAND_CUT);
  CHKAPPCMDCODE(APPCOMMAND_PASTE);
  CHKAPPCMDCODE(APPCOMMAND_REPLY_TO_MAIL);
  CHKAPPCMDCODE(APPCOMMAND_FORWARD_MAIL);
  CHKAPPCMDCODE(APPCOMMAND_SEND_MAIL);
  CHKAPPCMDCODE(APPCOMMAND_SPELL_CHECK);
  CHKAPPCMDCODE(APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE);
  CHKAPPCMDCODE(APPCOMMAND_MIC_ON_OFF_TOGGLE);
  CHKAPPCMDCODE(APPCOMMAND_CORRECTION_LIST);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_PLAY);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_PAUSE);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_RECORD);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_FAST_FORWARD);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_REWIND);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_CHANNEL_UP);
  CHKAPPCMDCODE(APPCOMMAND_MEDIA_CHANNEL_DOWN);
  CHKAPPCMDCODE(APPCOMMAND_DELETE);
  default:
    return L"APPCMD_NONE";
  }
#undef CHKAPPCMDCODE
}